# Generated by Django 4.2.16 on 2024-11-09 21:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodItemPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_bought", models.PositiveIntegerField()),
                ("month_bought", models.DateField(default=django.utils.timezone.now)),
                (
                    "amount_wasted",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "food_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="user.fooditem",
                    ),
                ),
            ],
        ),
    ]
