# Generated by Django 4.2.16 on 2024-11-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_fooditempurchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditempurchase",
            name="year_bought",
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name="fooditempurchase",
            name="month_bought",
            field=models.IntegerField(
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                    (11, 11),
                    (12, 12),
                ]
            ),
        ),
    ]
