# Generated by Django 4.2.16 on 2024-11-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_fooditempurchase_year_bought_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditempurchase",
            name="month_bought",
            field=models.IntegerField(
                choices=[
                    (1, "January"),
                    (2, "February"),
                    (3, "March"),
                    (4, "April"),
                    (5, "May"),
                    (6, "June"),
                    (7, "July"),
                    (8, "August"),
                    (9, "September"),
                    (10, "October"),
                    (11, "November"),
                    (12, "December"),
                ]
            ),
        ),
    ]
